[DEFAULT]
# Git-buildpackage configuration

pristine-tar = False
sign-tags = False

[buildpackage]
# Build configuration
export-dir = ../build-area/
ignore-new = True

# Don't clean by default (cmake handles this)
cleaner = true

